AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/NilComparison:
  Enabled: false
